apiVersion: v1
kind: Secret
metadata:
  labels:
    app: ci-config
  name: ci-config-secret
stringData:
  MAVEN_SERVER_USERNAME: admin
  MAVEN_SERVER_PASSWORD: admin123
  MAVEN_SERVER_HOST: http://nexus.cicd-tools.svc.cluster.local:8081
  SONAR_SERVER_HOST: http://sonarqube.cicd-tools.svc.cluster.local:9000
  GIT_USERNAME: pittar
  GIT_PASSWORD: notmypassword