namespace: petclinic-cicd

commonAnnotations:
  argocd.argoproj.io/sync-wave: "1"

# Nexus secret (username and password) and sonar host.
resources:
  - ci-config-secret.yaml
  - workspace-pvc.yaml
  - pipelines

# Generator options.
generatorOptions:
  labels:
    app: maven-settings
  disableNameSuffixHash: true

# Create a ConfigMap from custom settings.xml file.
configMapGenerator:
  - name: maven-settings-cm
    files:
      - settings.xml
