apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: build-app-
spec:
  pipelineRef:
    name: build-app
  params:
    - name: git-repo-url
      value: 'https://gitea-scm.apps.cluster-xlzjk.xlzjk.sandbox1013.opentlc.com/developer/petclinic.git'
    - name: gitops-repo-url
      value: 'https://gitea-scm.apps.cluster-xlzjk.xlzjk.sandbox1013.opentlc.com/developer/petclinic-gitops.git'
  taskRunTemplate:
    podTemplate:
      env:
        - name: MAVEN_SERVER_HOST
          valueFrom:
            secretKeyRef:
              name: ci-config-secret
              key: MAVEN_SERVER_HOST
        - name: MAVEN_SERVER_USERNAME
          valueFrom:
            secretKeyRef:
              name: ci-config-secret
              key: MAVEN_SERVER_USERNAME
        - name: MAVEN_SERVER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ci-config-secret
              key: MAVEN_SERVER_PASSWORD
        - name: GIT_USERNAME
          valueFrom:
            secretKeyRef:
              name: ci-config-secret
              key: GIT_USERNAME
        - name: GIT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ci-config-secret
              key: GIT_PASSWORD
  workspaces:
    - name: source
      persistentVolumeClaim:
        claimName: workspace
    - name: gitops
      persistentVolumeClaim:
        claimName: gitops-source
    - configMap:
        name: maven-settings-cm
      name: maven-settings
    - name: acs-central
      secret:
        secretName: roxsecrets