apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: prepare-prod-release-
spec:
  pipelineRef:
    name: prepare-prod-release
  params:
    - name: gitops-repo-url
      value: 'http://gitea.scm.svc.cluster.local:3000/developer/petclinic-gitops.git'
  taskRunTemplate:
    podTemplate:
      env:
        - name: MAVEN_SERVER_HOST
          valueFrom:
            secretKeyRef:
              name: ci-config-secret
              key: MAVEN_SERVER_HOST
        - name: MAVEN_SERVER_USERNAME
          valueFrom:
            secretKeyRef:
              name: ci-config-secret
              key: MAVEN_SERVER_USERNAME
        - name: MAVEN_SERVER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ci-config-secret
              key: MAVEN_SERVER_PASSWORD
        - name: GIT_USERNAME
          valueFrom:
            secretKeyRef:
              name: ci-config-secret
              key: GIT_USERNAME
        - name: GIT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ci-config-secret
              key: GIT_PASSWORD
  workspaces:
    - name: gitops
      persistentVolumeClaim:
        claimName: gitops
