apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-and-deploy-dev
spec:
  params:
    - default: 'http://gitea.scm.svc.cluster.local:3000/developer/petclinic.git'
      description: Source repository url.
      name: git-repo-url
      type: string
    - default: 'http://gitea.scm.svc.cluster.local:3000/developer/petclinic-gitops.git'
      description: Source repository url.
      name: gitops-repo-url
      type: string
    - default: quay.io/pittar/petclinic-demo
      description: External registry location to copy image to
      name: image_dest_url
      type: string
  tasks:
    - name: git-clone-source
      params:
        - name: url
          value: $(params.git-repo-url)
        - name: revision
          value: master
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: source
    - name: git-clone-gitops
      params:
        - name: url
          value: $(params.gitops-repo-url)
        - name: revision
          value: main
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: gitops
    - name: generate-id
      runAfter:
        - git-clone-source
        - git-clone-gitops
      taskRef:
        kind: ClusterTask
        name: generate-id
      workspaces:
        - name: source
          workspace: source
    - name: maven-pom-version
      params:
        - name: MAVEN_IMAGE
          value: 'quay.io/pittar/openjdk17-git:main'
        - name: VERSION_TYPE
          value: snapshot
        - name: PROXY_PROTOCOL
          value: http
        - name: CONTEXT_DIR
          value: .
      runAfter:
        - generate-id
      taskRef:
        kind: ClusterTask
        name: maven-pom-version
      workspaces:
        - name: source
          workspace: source
        - name: maven-settings
          workspace: maven-settings
    - name: maven
      params:
        - name: MAVEN_IMAGE
          value: 'quay.io/pittar/openjdk17-git:main'
        - name: GOALS
          value: 'package'
        - name: GIT_ENABLED
          value: 'true'
        - name: CONTEXT_DIR
          value: .
      runAfter:
        - maven-pom-version
      taskRef:
        kind: ClusterTask
        name: super-maven
      workspaces:
        - name: source
          workspace: source
        - name: maven-settings
          workspace: maven-settings
    - name: buildah
      params:
        - name: IMAGE
          value: '$(params.image_dest_url):latest'
        - name: STORAGE_DRIVER
          value: vfs
        - name: DOCKERFILE
          value: ./Containerfile
        - name: CONTEXT
          value: .
        - name: TLSVERIFY
          value: 'true'
        - name: FORMAT
          value: oci
        - name: BUILD_EXTRA_ARGS
          value: ''
        - name: PUSH_EXTRA_ARGS
          value: ''
        - name: SKIP_PUSH
          value: 'false'
      runAfter:
        - maven
      taskRef:
        kind: ClusterTask
        name: buildah
      workspaces:
        - name: source
          workspace: source
    - name: skopeo-copy
      params:
        - name: srcImageURL
          value: 'docker://$(params.image_dest_url):latest'
        - name: destImageURL
          value: >-
            docker://$(params.image_dest_url):$(tasks.maven-pom-version.results.pom-version)-$(tasks.generate-id.results.short-commit)
        - name: srcTLSverify
          value: 'true'
        - name: destTLSverify
          value: 'true'
      runAfter:
        - buildah
      taskRef:
        kind: ClusterTask
        name: skopeo-copy
      workspaces:
        - name: images-url
          workspace: source
    - name: acs-image-scan
      params:
        - name: image
          value: >-
            $(params.image_dest_url):$(tasks.maven-pom-version.results.pom-version)-$(tasks.generate-id.results.short-commit)
        - name: output_format
          value: table
      runAfter:
        - skopeo-copy
      taskRef:
        kind: ClusterTask
        name: acs-image-scan
      workspaces:
        - name: acs-central
          workspace: acs-central
    - name: acs-image-check
      params:
        - name: image
          value: >-
            $(params.image_dest_url):$(tasks.maven-pom-version.results.pom-version)-$(tasks.generate-id.results.short-commit)
      runAfter:
        - acs-image-scan
      taskRef:
        kind: ClusterTask
        name: acs-image-check
      workspaces:
        - name: acs-central
          workspace: acs-central
    - name: kustomize
      params:
        - name: image-name
          value: petclinic
        - name: new-image-name
          value: $(params.image_dest_url)
        - name: new-tag
          value: >-
            $(tasks.maven-pom-version.results.pom-version)-$(tasks.generate-id.results.short-commit)
        - name: overlaypath
          value: overlays/dev
      runAfter:
        - acs-image-check
      taskRef:
        kind: ClusterTask
        name: kustomize
      workspaces:
        - name: source
          workspace: gitops
    - name: push-dev-update
      params:
        - name: commands
          value: |
            git config --global user.email "pipeline@tekton.io"
            git checkout main
            git add -u
            git commit -m "Pushing"
            git push origin main
      runAfter:
        - kustomize
      taskRef:
        kind: ClusterTask
        name: git
      workspaces:
        - name: source
          workspace: gitops
    - name: argocd-task-sync-and-wait
      params:
        - name: application-name
          value: petclinic-dev
        - name: revision
          value: main
        - name: flags
          value: '--grpc-web'
        - name: argocd-version
          value: v2.2.2
      runAfter:
        - push-dev-update
      taskRef:
        kind: ClusterTask
        name: argocd-task-sync-and-wait
  workspaces:
    - name: source
    - name: gitops
    - name: maven-settings
    - name: acs-central
