apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: release
spec:
  params:
    - default: 'http://gitea.scm.svc.cluster.local:3000/developer/petclinic.git'
      description: Source repository url.
      name: git-repo-url
      type: string
    - default: 'http://gitea.scm.svc.cluster.local:3000/developer/petclinic-gitops.git'
      description: Source repository url.
      name: gitops-repo-url
      type: string
    - default: quay.io/pittar/petclinic-demo
      description: External registry location to copy image to
      name: image_dest_url
      type: string
  tasks:
    - name: git-clone-source
      taskRef:
        kind: ClusterTask
        name: git-clone
      params:
        - name: url
          value: $(params.git-repo-url)
        - name: revision
          value: master
      workspaces:
        - name: output
          workspace: source
    - name: git-clone-gitops
      taskRef:
        kind: ClusterTask
        name: git-clone
      params:
        - name: url
          value: $(params.gitops-repo-url)
        - name: revision
          value: main
      workspaces:
        - name: output
          workspace: gitops
    - name: maven-pom-version
      taskRef:
        kind: ClusterTask
        name: maven-pom-version
      runAfter:
        - git-clone-source
        - git-clone-gitops
      params:
        - name: MAVEN_IMAGE
          value: 'quay.io/pittar/openjdk17-git:main'
        - name: VERSION_TYPE
          value: 'release'
        - name: CONTEXT_DIR
          value: .
      workspaces:
        - name: source
          workspace: source
        - name: maven-settings
          workspace: maven-settings
    - name: maven
      taskRef:
        kind: ClusterTask
        name: super-maven
      runAfter:
        - maven-pom-version
      params:
        - name: MAVEN_IMAGE
          value: 'quay.io/pittar/openjdk17-git:main'
        - name: GOALS
          value: 'release:prepare release:perform -DskipTests -Darguments=-DskipTests'
        - name: GIT_ENABLED
          value: 'true'
        - name: CONTEXT_DIR
          value: .
      workspaces:
        - name: source
          workspace: source
        - name: maven-settings
          workspace: maven-settings
    - name: buildah
      taskRef:
        kind: ClusterTask
        name: buildah
      runAfter:
        - maven
      params:
        - name: IMAGE
          value: '$(params.image_dest_url):latest'
        - name: STORAGE_DRIVER
          value: vfs
        - name: DOCKERFILE
          value: ./Containerfile
        - name: CONTEXT
          value: .
        - name: TLSVERIFY
          value: 'true'
        - name: FORMAT
          value: oci
        - name: SKIP_PUSH
          value: 'false'
      workspaces:
        - name: source
          workspace: source
    - name: skopeo-copy
      taskRef:
        kind: ClusterTask
        name: skopeo-copy
      runAfter:
        - buildah
      params:
        - name: srcImageURL
          value: 'docker://$(params.image_dest_url):latest'
        - name: destImageURL
          value: >-
            docker://$(params.image_dest_url):$(tasks.maven-pom-version.results.pom-version)
        - name: srcTLSverify
          value: 'true'
        - name: destTLSverify
          value: 'true'
      workspaces:
        - name: images-url
          workspace: source
    - name: acs-image-scan
      taskRef:
        kind: ClusterTask
        name: acs-image-scan
      runAfter:
        - skopeo-copy
      params:
        - name: image
          value: >-
            $(params.image_dest_url):$(tasks.maven-pom-version.results.pom-version)
        - name: output_format
          value: table
      workspaces:
        - name: acs-central
          workspace: acs-central
    - name: acs-image-check
      taskRef:
        kind: ClusterTask
        name: acs-image-check
      runAfter:
        - acs-image-scan
      params:
        - name: image
          value: >-
            $(params.image_dest_url):$(tasks.maven-pom-version.results.pom-version)
      workspaces:
        - name: acs-central
          workspace: acs-central
    - name: kustomize
      taskRef:
        kind: ClusterTask
        name: kustomize
      runAfter:
        - acs-image-check
      params:
        - name: image-name
          value: petclinic
        - name: new-image-name
          value: $(params.image_dest_url)
        - name: new-tag
          value: $(tasks.maven-pom-version.results.pom-version)
        - name: overlaypath
          value: overlays/prod
      workspaces:
        - name: source
          workspace: gitops
    - name: push-dev-update
      taskRef:
        kind: ClusterTask
        name: git-cli
      runAfter:
        - kustomize
      params:
        - name: commands
          value: |
            git config --global user.email "pipeline@tekton.io"
            git add -u
            git commit -m "Pushing release version to dev."
            git push origin main
      workspaces:
        - name: source
          workspace: gitops
    - name: argocd-task-sync-and-wait
      params:
        - name: application-name
          value: petclinic-dev
        - name: revision
          value: main
        - name: flags
          value: '--grpc-web'
        - name: argocd-version
          value: v2.2.2
      runAfter:
        - push-dev-update
      taskRef:
        kind: ClusterTask
        name: argocd-task-sync-and-wait
  workspaces:
    - name: source
    - name: gitops
    - name: maven-settings
    - name: acs-central
